linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - unparam
    - vet
    - vetshadow
issues:
  exclude:
    - "returns unexported type"
    - "unlambda"
    - "should rewrite http.NewRequestWithContext"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - scopelint
        - goerr113
        - funlen
        - gocognit
        - cyclop
  include:
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
run:
  go: "1.20"
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: camel